/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import configuration.DatabaseTypes;
import controllers.ProdutoController;
import entity.Produto;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author cliente
 */
public class ProdutoDetails extends javax.swing.JFrame {
    // Produto a ser detalhado
    private Produto produto;
    // Controller
    private ProdutoController controller;
    
    /**
     * Cria um novo detalhamento do produto
     * 
     * @param produto the produto has been detailed
     */
    public ProdutoDetails(Produto produto) {
        initComponents();
        // Não faz nada ao fechar
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        // Dados
        this.produto = produto;
        // Controller
        this.controller = new ProdutoController(DatabaseTypes.MYSQL);
        
        // Seta com informações do produto
        nome.setText(this.produto.getNome());
        quantidade.setText(this.produto.getQuantidade().toString());
        preco.setText(this.produto.getPrecoUnidade().toString());
        
        
        
        
    }

    private ProdutoDetails() {
        initComponents();
        // Não faz nada ao fechar
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);// Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        minus = new javax.swing.JButton();
        quantidade = new javax.swing.JLabel();
        plus = new javax.swing.JButton();
        preco = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        deletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Quantidade");

        jLabel3.setText("Preço Por Unidade");

        nome.setPreferredSize(new java.awt.Dimension(120, 25));

        minus.setText("<");
        minus.addActionListener(this::minusActionPerformed);

        quantidade.setText("0");

        plus.setText(">");
        plus.addActionListener(this::plusActionPerformed);

        preco.setPreferredSize(new java.awt.Dimension(120, 25));

        save.setText("Salvar");
        save.addActionListener(this::saveActionPerformed);

        exit.setText("Sair");
        exit.addActionListener(this::exitActionPerformed);

        deletar.setText("Deletar");
        deletar.addActionListener(this::deletarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit))
                    .addComponent(deletar))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(minus)
                    .addComponent(quantidade)
                    .addComponent(plus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(exit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletar)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Sai da tela
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    // Atualiza o produto
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        
        produto.setNome(nome.getText());
        produto.setQuantidade(Integer.valueOf(quantidade.getText()));
        produto.setPrecoUnidade(Float.valueOf(preco.getText()));
        
        this.controller.update(produto.getId(), produto);
    }//GEN-LAST:event_saveActionPerformed

    // Diminui a quantidade
    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
        int number = Integer.parseInt(quantidade.getText());
        
        if(number > 0) --number;
        
        quantidade.setText(Integer.toString(number));
    }//GEN-LAST:event_minusActionPerformed

    // Aumenta
    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        int number = Integer.parseInt(quantidade.getText());
        
        ++number;
        
        quantidade.setText(Integer.toString(number));
    }//GEN-LAST:event_plusActionPerformed

    // Deleta
    private void deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarActionPerformed
        // TODO add your handling code here:
        
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente deletar "+produto.getNome()+"?", "Confirmação", JOptionPane.YES_NO_OPTION);
                
        // Deleta apenas se o usuário quiser
        if(opcao == JOptionPane.YES_OPTION){
            controller.delete(produto.getId());
                
            dispose();
        }
       
        
        
        
        
        
    }//GEN-LAST:event_deletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            System.out.println("Erro:"+ex.getMessage());
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProdutoDetails().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletar;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton minus;
    private javax.swing.JTextField nome;
    private javax.swing.JButton plus;
    private javax.swing.JTextField preco;
    private javax.swing.JLabel quantidade;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
